apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
data:
  envoy.yaml: |-
      static_resources:
        listeners:
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 8080
          filter_chains:
          - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: egress
                route_config:
                  name: local_route
                  virtual_hosts:
                  - name: backend
                    domains:
                    - "*"
                    routes:
                    - match: { prefix: "/" }
                      request_headers_to_add:
                      - header:
                          key: "kubernetes-route-as"
                          value: "nicovanh-9699"
                        append: true
                      route: { cluster: greet-envoy, timeout: 120s }  
                http_filters:
                - name: envoy.filters.http.router
        clusters:
        - name: greet-envoy
          connect_timeout: 35s
          type: strict_dns
          dns_lookup_family: V4_ONLY
          lb_policy: round_robin
          hosts:
            - socket_address:
                address: greet-api-envoy
                port_value: 8000
      admin:
        access_log_path: "/dev/null"
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 8001
      layered_runtime:
        layers:
          - name: static_layer_0
            static_layer:
              envoy:
                resource_limits:
                  listener:
                    example_listener_name:
                      connection_limit: 10000