{{- $servicePort := .Values.ingress.port -}}
{{- $serviceName := .Values.name -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Values.name}}-ingress
  labels:
    app.kubernetes.io/managed-by: helm
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    meta.helm.sh/release-name: {{ $serviceName }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - backend:
            serviceName: {{ $serviceName }}
            servicePort: {{ $servicePort }}
          path: /
