apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: ClusterIP
  ports:
    - name: envoy-port
      port: {{ .Values.ingress.port }}
      targetPort: {{ .Values.ingress.port }}
   
  selector:
    app: {{ .Values.name }}