
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
data:
  envoy.yaml: |-
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 8000
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: auto
              stat_prefix: greet_proxy
              route_config:
                name: local_route
                virtual_hosts:
                - name: service
                  domains:
                  - "*" 
                  routes:      
                  - match: { prefix: "/" }
                    route: { cluster: greet_service, max_grpc_timeout: 120s }                              
              http_filters: 
              - name: envoy.filters.http.grpc_json_transcoder
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
                  proto_descriptor: "/config/protos/greet.pb"
                  services: ["greet.Greeter",]
                  match_incoming_request_route: true
                  print_options:
                    add_whitespace: true
                    always_print_primitive_fields: true
                    always_print_enums_as_ints: false
                    preserve_proto_field_names: false              
              - name: envoy.filters.http.router         

      clusters:
      - name: greet_service
        connect_timeout: 120s
        type: logical_dns
        lb_policy: round_robin
        http2_protocol_options: {}          
        load_assignment:
          cluster_name: greet_service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: greet-api
                    port_value: 8100
                    
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8081
