apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-proto-config
binaryData:
  {{- $files := .Files }}
  {{- range .Values.protos }}
  {{- $proto := . }}
  {{- range tuple $proto }}
  {{ . }}: |-
    {{ $files.Get . | b64enc }}
  {{- end }}
  {{- end }}