apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: ClusterIP
  ports:
    - name: envoy-port
      port: 8000
      targetPort: 8000
   
  selector:
    app: {{ .Values.name }}